"""add feedback_helpful to chat_history

Revision ID: f7dbe969141c
Revises: af8c2d1da839
Create Date: 2026-08-06 00:26:54.920018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7dbe969141c'
down_revision: Union[str, Sequence[str], None] = 'af8c2d1da839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('feedback_helpful', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'feedback_helpful')
    # ### end Alembic commands ###
